/* functions/_shared/headers.js — T3.6b (#150): the ONE security-header set for EVERY Pages
   Function response. Pages `_headers` do NOT apply to Functions responses (the same inert-file
   mechanism `_redirects` documents), so /c, /og and /api/release must each carry these explicitly,
   on every return path incl. cached replays and early returns. MIRROR OF public/_headers' /* block
   — keep the two in lockstep when either changes. */
export const SEC_HEADERS = {
  'X-Frame-Options': 'DENY',
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Content-Security-Policy': "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; script-src 'self' 'report-sample' 'sha256-8yra1+kbhTOMSaNpjrlflT/SNWie1M3Sw9x7uG2UzRs=' 'sha256-xNp+s0hernL9RiOFjppcfwwu9lmhdiyDd2XkmpgEtNk=' 'sha256-kVm7fpjHHqV0ftWKYtcDW9Tfpla4jEjac+EnjKvw27w=' 'sha256-1fpWO5MNDf2mjCBw30D6NH7a81GxC+nAV17bIaaiDBk=' 'sha256-vSnWJ9XSMTKTr2kVfzKQyJmEz8SJ+09Jzm3/sDSm+Ms=' https://clerk.traxwax.com https://cloud.umami.is https://static.cloudflareinsights.com https://challenges.cloudflare.com; worker-src 'self' blob:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https:; connect-src 'self' https://sfipqknrbvamwwahwxnl.supabase.co https://clerk.traxwax.com https://cloud.umami.is https://gateway.umami.is https://challenges.cloudflare.com https://clerk-telemetry.com; frame-src 'self' https://clerk.traxwax.com https://challenges.cloudflare.com; form-action 'self' https://clerk.traxwax.com; report-uri /api/csp-report; report-to csp-endpoint",
  'Content-Security-Policy-Report-Only': "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; script-src 'self' 'report-sample' 'sha256-8yra1+kbhTOMSaNpjrlflT/SNWie1M3Sw9x7uG2UzRs=' 'sha256-xNp+s0hernL9RiOFjppcfwwu9lmhdiyDd2XkmpgEtNk=' 'sha256-kVm7fpjHHqV0ftWKYtcDW9Tfpla4jEjac+EnjKvw27w=' 'sha256-1fpWO5MNDf2mjCBw30D6NH7a81GxC+nAV17bIaaiDBk=' 'sha256-vSnWJ9XSMTKTr2kVfzKQyJmEz8SJ+09Jzm3/sDSm+Ms=' https://clerk.traxwax.com https://cloud.umami.is https://static.cloudflareinsights.com https://challenges.cloudflare.com; worker-src 'self' blob:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https://i.discogs.com https://img.clerk.com; connect-src 'self' https://sfipqknrbvamwwahwxnl.supabase.co https://clerk.traxwax.com https://cloud.umami.is https://gateway.umami.is https://challenges.cloudflare.com https://clerk-telemetry.com; frame-src 'self' https://clerk.traxwax.com https://challenges.cloudflare.com; form-action 'self' https://clerk.traxwax.com; report-uri /api/csp-report; report-to csp-endpoint",
  'Reporting-Endpoints': 'csp-endpoint="https://traxwax.com/api/csp-report"',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), interest-cohort=()',
};
